name: Build EXE with GUI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean environment and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y PySimpleGUI
          pip install PySimpleGUI==4.60.8 pdfplumber pyinstaller
          rmdir /s /q build
          rmdir /s /q dist
          del /f /q *.spec

      - name: Build EXE
        run: pyinstaller --onefile --noconsole buscador_pdf.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: buscador_pdf_exe
          path: dist/buscador_pdf.exe
